version: "3.8"

services:

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - POSTGRES_DB=seu_banco
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      rede_banco:
        ipv4_address: 172.16.2.3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.api
      target: build
    container_name: api
    depends_on:
      - postgres
    command: npm run start
    ports:
      - 4000:4000
    networks:
      rede_banco:
        ipv4_address: 172.16.2.2

  front:
    build:
      context: ./front-react
      dockerfile: Dockerfile.front
      target: prod
    container_name: front
    depends_on:
      - api
    ports:
      - 9090:80
    networks:
      rede_front:
        ipv4_address: 172.16.1.3

networks:
  rede_front:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.1.0/24
  rede_banco:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.2.0/24

volumes:
  postgres-data:
